name: fdfd

on:
  workflow_dispatch:
    inputs:
      blam:
        description: 'Environment to deploy to'
        required: true
        default: 'val.yaml'

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4

      - name: Set env
        run: echo "SHORT_SHA=1371355" >> $GITHUB_ENV
      
      - name: With checkout
        run: |
          echo ${{ env.SHORT_SHA }}
          if [[ $(yq eval .deploy.image.tag ${{ github.event.inputs.blam }}) -ne ${{ env.SHORT_SHA }} ]]; then
            echo "Equals"
          else
            echo "Ne"
          fi  
          
      
