name: fdfd

on: push

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: Compare
        run: |
          if [[ endsWith('$(cat long.tx)', '$(cat short.tx))' ]]; then
            echo "Hello"
          else
            echo "No!"
          fi    
          
