name: fdfd

on: push

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: With checkout
        run: |
          echo hello > f.out
          ls -lah
    

  job2:
    needs: dfdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
        
      - name: Again with checkout
        run: ls -lah
          
