name: fdfd

on:
  workflow_dispatch:
    inputs:
      blam:
        description: 'Environment to deploy to'
        required: true
        default: 'val.yaml'

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: With checkout
        run: |
          if [[ $(yq eval .deploy.image.tag ${{ github.event.inputs.blam }}) -ne 1371355 ]]; then
            echo "Equals"
          else
            echo "Ne"
          fi  
          
      
