name: fdfd

on: push

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: Compare
        run: |
          diff long.tx short.tx
          
