name: fdfd

on: push

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Git Setup  
        shell: bash
        run: |
          echo "Git setup"
          pwd
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'
          
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: With checkout
        run: |
          if [[ diff long.tx short.tx ]]; then
            echo equal
          else
            echo not equal
          fi  
    

  job2:
    needs: dfdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
        
      - name: Again with checkout
        run: ls -lah
          
