name: fdfd

on: push

jobs:
  dfdf:
    runs-on: ubuntu-latest

    steps:
      - name: Git Setup  
        shell: bash
        run: |
          echo "Git setup"
          pwd
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'
          
      - name: Checkout primary repo
        uses: actions/checkout@v4
      
      - name: With checkout
        env:
          GITHUB_TOKEN: "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"
        run: |
          echo hello > fn.out
          ls -lah
          git status
          git add .
          git commit -m "commit message"
          git push
    

  job2:
    needs: dfdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4
        
      - name: Again with checkout
        run: ls -lah
          
