name: fdfd

on:
  workflow_dispatch:
    inputs:
      blam:
        description: 'Environment to deploy to'
        required: true
        default: 'val.yaml'

jobs:
  dfdf:
    runs-on: self-hosted

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4

      - name: Set env
        run: echo "Hello from action"
      
