name: Apply terraform infrastructure

on:
  push:
    branches:
    - main
    paths:
    - 'fold/**'
  workflow_dispatch:

jobs:
  Terraform-job:
    name: Tf-job-name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set env
        run: |
          pwd
          ls -lah
          echo "Hello from action"
      
